ktor:
    application:
        modules:
            - dev.flomik.ApplicationKt.module
    deployment:
        port: 8080
race:
    reconnect-grace-ms: 45000
    persistence:
        enabled: true
        file: ./race-server-data/state.json
