ktor:
    application:
        modules:
            - dev.flomik.ApplicationKt.module
    deployment:
        port: 8080
race:
    reconnect-grace-ms: 45000
    ping-timeout-ms: 180000
    target-items-file: ""
    persistence:
        enabled: true
        provider: file
        file: ./race-server-data/state.json
        postgres:
            url: jdbc:postgresql://localhost:5432/itemrace
            user: itemrace
            password: itemrace
